name: Hello workflow

on: push

jobs:
  job1:
   runs-on: ubuntu-latest

   steps:
     - name: First Job
       run: echo "first job"

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
     - name: Second Job
       run: echo "second job"
